/**
 * Users */

export const SET_USERS = 'SET_USERS';

export const FETCHING_USERS_START = 'FETCHING_USERS_START';
export const FETCHING_USERS_SUCCESS = 'FETCHING_USERS_SUCCESS';
export const FETCHING_USERS_ERROR = 'FETCHING_USERS_ERROR';
